# Generated by Django 3.2 on 2021-05-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_clickstat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='copyright',
            options={'verbose_name': 'Copyright', 'verbose_name_plural': 'Copyrights'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Reciep', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipereview',
            options={'ordering': ['created'], 'verbose_name': 'recipe review', 'verbose_name_plural': 'recipe review'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='topicreview',
            options={'ordering': ['created'], 'verbose_name': 'Topic review', 'verbose_name_plural': 'Topic reviews'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True, verbose_name='Category description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='clickstat',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='copyright',
            name='copyright_text',
            field=models.TextField(verbose_name='COpyright description'),
        ),
        migrations.AlterField(
            model_name='copyright',
            name='copyright_title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(verbose_name='Ingredient description'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(default='Title', max_length=50, unique=True, verbose_name='Ingredient title'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe_app.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredient', to='recipe_app.Ingredient', verbose_name='ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_text',
            field=models.TextField(verbose_name='Recipe description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Recipe title'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.SlugField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='body',
            field=models.TextField(max_length=5000, verbose_name='Review body'),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipereview',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='recipe_app.recipe', verbose_name='recipe'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='recipe_app.Recipe', verbose_name='recipe'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_text',
            field=models.TextField(verbose_name='Topic text'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Topic title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='url',
            field=models.SlugField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topicreview',
            name='body',
            field=models.TextField(max_length=5000, verbose_name='Review body'),
        ),
        migrations.AlterField(
            model_name='topicreview',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='topicreview',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='topicreview',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='recipe_app.topic', verbose_name='topic'),
        ),
    ]
