# Generated by Django 3.2 on 2021-05-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_auto_20210506_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipereview',
            name='email',
        ),
        migrations.RemoveField(
            model_name='topicreview',
            name='email',
        ),
    ]
