# Generated by Django 3.1.4 on 2021-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_auto_20210130_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(default='Title', max_length=50, unique=True, verbose_name='Название продукта/ингридиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название статьи'),
        ),
    ]
