# Generated by Django 3.2 on 2021-04-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_auto_20210428_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='topicimage',
            name='topic',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ManyToManyField(related_name='recipe_image', to='recipe_app.RecipeImage', verbose_name='images'),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='title',
            field=models.CharField(default='title', max_length=50, verbose_name='Image title'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ManyToManyField(related_name='topic_image', to='recipe_app.TopicImage', verbose_name='images'),
        ),
        migrations.AddField(
            model_name='topicimage',
            name='title',
            field=models.CharField(default='title', max_length=50, verbose_name='Image title'),
        ),
    ]
