# Generated by Django 3.2 on 2021-04-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_auto_20210429_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='topicimage',
            name='title',
        ),
    ]
