# Generated by Django 3.2 on 2021-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0011_auto_20210430_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipe/', verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, upload_to='topic/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
        migrations.DeleteModel(
            name='TopicImage',
        ),
    ]
