# Generated by Django 3.2 on 2021-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0012_auto_20210430_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='draft',
            field=models.BooleanField(default=True, null=True, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic/', verbose_name='Изображение'),
        ),
    ]
