# Generated by Django 3.2 on 2021-05-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0013_auto_20210430_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='draft',
            field=models.BooleanField(default=False, null=True, verbose_name='Черновик'),
        ),
    ]
