# Generated by Django 3.1.4 on 2020-12-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutInfo',
        ),
        migrations.RenameModel(
            old_name='Copyright',
            new_name='CopyrightInfo',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductInfo',
        ),
        migrations.RenameModel(
            old_name='Recipe',
            new_name='RecipeInfo',
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='TopicInfo',
        ),
    ]
