# Generated by Django 3.1.4 on 2021-01-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_recipe', '0002_auto_20210122_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingridient', to='main_recipe.Ingredient', verbose_name='рецепт'),
        ),
    ]
