# Generated by Django 3.1.4 on 2021-01-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_recipe', '0003_auto_20201226_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutInfo',
        ),
    ]
