# Generated by Django 3.1.4 on 2021-01-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_recipe', '0004_delete_aboutinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Category')),
            ],
        ),
        migrations.RenameModel(
            old_name='CopyrightInfo',
            new_name='Copyright',
        ),
        migrations.RenameModel(
            old_name='ProductInfo',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='RecipeInfo',
            new_name='Recipe',
        ),
        migrations.RenameModel(
            old_name='TopicInfo',
            new_name='Topic',
        ),
    ]
