# Generated by Django 3.1.4 on 2021-01-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_recipe', '0006_recipe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='copyright',
            options={'verbose_name': 'Авторские права', 'verbose_name_plural': 'Авторские права'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='product_title',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default='Description', verbose_name='Описание продукта/ингридиента'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(null=True, upload_to='ingredient/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='title',
            field=models.CharField(default='Title', max_length=50, verbose_name='название продукта/ингридиента'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipe/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, upload_to='topic/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='topic',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='main_recipe.Recipe', verbose_name='рецепт'),
        ),
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='copyright',
            name='copyright_text',
            field=models.TextField(verbose_name='Описание авторских прав'),
        ),
        migrations.AlterField(
            model_name='copyright',
            name='copyright_title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_text',
            field=models.TextField(verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_title',
            field=models.CharField(max_length=100, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_title',
            field=models.CharField(max_length=150, verbose_name='Название статьи'),
        ),
    ]
