# Generated by Django 3.1.4 on 2021-01-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_recipe', '0007_auto_20210130_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipereview',
            options={'ordering': ['created'], 'verbose_name': 'отзыв о рецепте', 'verbose_name_plural': 'отзывы о рецепте'},
        ),
        migrations.AlterModelOptions(
            name='topicreview',
            options={'ordering': ['created'], 'verbose_name': 'отзыв о статье', 'verbose_name_plural': 'отзывы о статье'},
        ),
    ]
